version: '3'
services:
    database:
        image: mariadb:10.6
        container_name: 'dbhost'
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'secretsofuser'
            MYSQL_ROOT_PASSWORD: 'secretsofroot'
        volumes:
            - ./db:/var/lib/mysql
            - ./init/mysql:/docker-entrypoint-initdb.d
        networks:
            - internal

    phpmyadmin:
        image: phpmyadmin:latest
        depends_on:
            - database
        container_name: 'phpmyadmin'
        ports:
            - '8090:80'

        environment:
            PMA_HOST: 'dbhost'
            PMA_USER: 'root'
            PMA_PASSWORD: 'secretsofroot'
        networks:
            - internal
    artemis:
        image: quay.io/artemiscloud/activemq-artemis-broker
        domainname: 'artemis'
        container_name: 'artemis'
        depends_on:
            - database
        ports:
            - "8161:8161"
            - "61616:61616"
            - "5672:5672"
        environment:
            AMQ_USER: admin
            AMQ_PASSWORD: secretsofadmin
        networks:
            - internal

    webapplication:
        image: pizzaservice.webapplication
        depends_on:
            - database
            - artemis
        container_name: 'app'
        ports:
            - '8080:8080'
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://dbhost:3306/pizzadb
            - SPRING_DATASOURCE_USERNAME=user
            - SPRING_DATASOURCE_PASSWORD=secretsofuser
            - SPRING_PROFILES_ACTIVE=mysql
            - SPRING_ARTEMIS_BROKER_URL=tcp://artemis:61616
            - SPRING_ARTEMIS_USER=admin
            - SPRING_ARTEMIS_PASSWORD=secretsofadmin
        networks:
            - internal

    workflowservice:
        image: pizzaservice.workflowservice
        depends_on:
            - webapplication
            - artemis
        container_name: 'workflowservice'
        ports:
            - '8081:8081'
        environment:
            - SPRING_ARTEMIS_BROKER_URL=tcp://artemis:61616
            - SPRING_ARTEMIS_USER=admin
            - SPRING_ARTEMIS_PASSWORD=secretsofadmin
        networks:
            - internal

    prometheus:
        image: 'prom/prometheus:latest'
        container_name: 'prometheus'
        depends_on:
            - database
            - webapplication
        ports:
            - '9090:9090'
        command: '--config.file=/etc/prometheus/config.yml'
        volumes:
            - './init/prometheus/prometheus.yml:/etc/prometheus/config.yml'
        networks:
            - internal

    grafana:
        depends_on:
            - prometheus
        image: 'grafana/grafana:latest'
        container_name: 'grafana'
        ports:
            - '3000:3000'
        networks:
            - internal
        volumes:
            - './init/grafana/prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml'

networks:
    internal:
