spring.datasource.url: jdbc:h2:file:./camunda-h2-database
server:
  port: 8081
camunda.bpm.admin-user:
  id: demo
  password: demo

spring:
  artemis:
    broker-url=tcp://localhost:61616
    user=admin
    password=secretsofadmin

jms:
  orderitem:
    kitchen_incoming_queue: KitchenIncomingOrderItemQueue
    kitchen_outgoing_queue: KitchenOutgoingOrderItemQueue