spring.datasource.url: jdbc:h2:file:./camunda-h2-database
server:
  port: 8081
camunda.bpm.admin-user:
  id: demo
  password: demo


pizzaservice:
  jms:
    kitchen_incoming_queue: KitchenIncomingQueue
    kitchen_outgoing_queue: KitchenOutgoingQueue